server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  profiles:
    active: native
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared