server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guxueliang/springclouddemo.git
          searchPaths: config
          username: guxueliang
          password: 123abc,..,
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/